name: Test

# Triggered when pushing or creating a pull request
on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch

# Job definition
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 for a Kotlin or Java project
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build and run tests
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Archive test reports
      - name: Archive test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests/test